steps:
  # 1. Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/data-architecture-demo/data-etl:latest', '.']

  # 2. Push da imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/data-architecture-demo/data-etl:latest']

  # 3. Deploy como Cloud Run Job
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'jobs', 'deploy', 'data-etl-job',
        '--image', '$_REGION-docker.pkg.dev/$PROJECT_ID/data-architecture-demo/data-etl:latest',
        '--region', '$_REGION',
        '--max-retries', '0'
      ]

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/data-architecture-demo/data-etl:latest'

substitutions:
  _REGION: 'southamerica-east1'
